okex/cosmos-sdk

server/config/config_okchain.go
server/util.go

Closes: #XXX
______
______
For admin use:

fix backend default config

---

x/mock/app.go

fix the mock test func

---

server/config/config.go

set default min-gas-prices

---

config/default_params.go

Fix issue 47 in okchain by removing param `MinSelfDelegationLimited`  in config/default_params.go.
______
For Admin Use:

FIX: issue 47 of okchain, remove param msdLimited in config/default_params.go

---

x/auth/types/stdtx.go

add fee schema

---

x/auth/ante.go

To fix okchain issue #70 && order tx not requiring fees

---

server/config/toml.go

add go template function "js" to the item of file path

---

version/version.go

- adapt the issue https://github.com/okex/okchain/issues/59
______
For Admin Use:

fix the missing content in version output

---

types/coin.go

check the format of pooltoken

---

types/coin_test.go
x/crisis/handler.go
x/crisis/handler_test.go

close crisis and fix UT

---

baseapp/baseapp.go

fix bug:delete redundant events

---

types/coin.go

poolswap -> ammswap

---

client/keys/add_ledger_test.go
client/keys/show_test.go
crypto/keys/keybase_test.go
crypto/keys/lazy_keybase_test.go
crypto/keys/types_test.go
crypto/ledger_test.go
server/config/config_okchain.go
server/start.go
server/start_okchain.go
server/util.go
types/address.go
types/rest/rest_test.go
x/bank/internal/types/msgs_test.go
x/genutil/legacy/v036/migrate_test.go
x/gov/types/codec.go
x/slashing/client/cli/query.go
x/slashing/types/expected_keepers.go
x/slashing/types/msg_test.go

okchain -> okexchain

---

server/config/config.go
server/config/config_okchain.go
server/config/toml.go
server/start_okchain.go

add stream flag

---

client/keys/add_ledger_test.go
client/keys/show_test.go
crypto/keys/keybase_test.go
crypto/keys/lazy_keybase_test.go
crypto/keys/types_test.go
crypto/ledger_test.go
server/config/config.go
server/config/config_okchain.go
server/config/toml.go
server/start.go
server/start_okchain.go
server/util.go
types/address.go
types/coin.go
types/rest/rest_test.go
x/bank/internal/types/msgs_test.go
x/genutil/legacy/v036/migrate_test.go
x/gov/types/codec.go
x/slashing/client/cli/query.go
x/slashing/types/expected_keepers.go
x/slashing/types/msg_test.go

merge stream

---

simapp/utils.go
x/mint/abci.go
x/mint/alias.go
x/mint/beginBlocker_test.go
x/mint/genesis.go
x/mint/genesis_test.go
x/mint/internal/keeper/keeper.go
x/mint/internal/types/cache_okchain.go
x/mint/internal/types/minter.go
x/mint/internal/types/minter_okchain.go
x/mint/internal/types/params.go

Deflation mode

---

x/mint/abci.go
x/mint/beginBlocker_test.go

fix mint zero bug

---

client/keys/add_ledger_test.go
client/keys/show_test.go
crypto/keys/keybase_test.go
crypto/keys/lazy_keybase_test.go
crypto/keys/types_test.go
crypto/ledger_test.go
run.sh
types/rest/rest_test.go
x/bank/internal/types/msgs_test.go
x/genutil/legacy/v036/migrate_test.go
x/slashing/types/msg_test.go

v0.37.9 patched fix ut

---

types/coin.go
types/dec_coin.go

add regular match for pool token

---

server/start_okchain.go
server/util.go

3 seconds for default timeout commit

---

crypto/keys/keybase.go

recover account by prikey

---

x/mint/beginBlocker_test.go
x/mint/internal/keeper/keeper.go

change amount of original minted per block from 0.05 to 0.5

---

types/coin_okchain.go

add type SysCoins = DecCoins

---

server/util.go

Change okchain to okexchain

---

x/mint/internal/types/params.go

Correct spelling errors:inflation-->deflation

---

client/lcd/root.go
server/start_okchain.go

FINISH: integrate web3 rest with the start of node

---

crypto/keys/output.go

print eth_address when add key or list key

---

baseapp/helpers_okchain.go

Add getDeliverStateCtx function to helpers_okchain.go

---

types/aliase_coin_okchain.go
types/coin.go

fix coins compare func

---

server/util.go

enable log_file and log_stdout

---

store/rootmulti/store.go

start block height

---

client/keys/add.go
crypto/keys/keybase_base.go
crypto/keys/keybase_base_okchain.go

recover by privkey

---

client/keys/add.go
crypto/keys/keybase_base.go
crypto/keys/keybase_base_okchain.go

support the recovery of accounts via private keys

---

server/start_okchain.go

add some flags about unlock account 

---

types/errors/abci.go

fix panic no prompt message

---

types/errors_okexchain.go

fix error not display code and error message

---

x/auth/ante/fee.go
x/auth/types/txbuilder.go

remove ceil when calculate the fees

---

server/config/config.go

add defaultMinGasPrices

---

types/staking.go

tokt to okt

---

server/start_okchain.go

rest path prefix flag

---

client/context/query.go
types/errors_okexchain.go

Closes: #XXX
______
______
For admin use:

 return response when the query encounters an error

---

x/supply/internal/keeper/bank.go
x/supply/internal/types/expected_keepers.go

Closes: #XXX
______
______
For admin use:

add blackList check in function SendCoinsFromModuleToAccount

---

x/supply/internal/keeper/bank.go

Closes: #XXX
______
______
For admin use:

Address in blacklist is not allowed

---

simapp/app.go
x/supply/internal/keeper/bank_test.go

Closes: #XXX
______
______
For admin use:

add ut for checking black list

---

client/keys/add.go

Closes: #XXX
______
______
For admin use:

Eth hdpath

---

x/auth/ante/sigverify.go

Closes: #XXX
______
______
For admin use:

add sign msg to error response

---

types/address.go
types/address_test.go

Closes: #XXX
compate 0x address to send and query
more detail : https://github.com/okex/ethermint/issues/325
______
______
For admin use:

compate 0x address to send and query

---

x/supply/genesis.go
x/supply/internal/keeper/invariants.go

x/supply: change the invariant judgement, ignoring the coin of zero value

---

server/config/config.go

Closes: #XXX
______
______
For admin use:

FINISH: standardize the min-gas-prices in generation of okexchaind.toml

---

.gitignore
types/milestone.go
types/version.go
x/bank/handler.go

Closes: #XXX
______
______
For admin use:

add block height control

---

server/start.go

FINISH: add flag for tendermint/port monitors

---

server/start.go

add flags when start exporting evm data

---

types/milestone.go
x/bank/handler.go

Closes: #XXX
______
______
For admin use:

refactor func HigherThanMercury a bit

---

server/export.go
server/start.go

Closes: #XXX
______
______
For admin use:

add flag for export and import evm

---

server/export.go
server/start.go

Closes: #XXX
______
______
For admin use:

add goroutine-num flag

---

server/start.go
server/util.go

Closes: #XXX
______
______
For admin use:

add registerAppFlagFn

---

x/mint/internal/types/params.go

Closes: #XXX
______
______
For admin use:

add annotation for mint params

---

client/lcd/root.go

Closes: #XXX
______
______
For admin use:

set rest-server log to okexchaind log file

---

store/iavl/store.go

Closes: #XXX
______
______
For admin use:

update iavl store for concurrent safe

---

store/cachekv/store.go

Closes: #XXX
______
______
For admin use:

Backport KVCache speeds ups to launchpad https://github.com/cosmos/cosmos-sdk/pull/8723

---

baseapp/baseapp.go
store/iavl/store.go
store/iavl/tree.go
store/rootmulti/store.go

Closes: #XXX
______
______
For admin use:

add export for baseapp

---

server/pruning.go
server/start.go
store/rootmulti/store.go
store/types/pruning.go

Closes: #XXX
______
______
For admin use:

add flag pruning-max-retain-num

---

server/pruning.go
server/start.go

Closes: #XXX
______
______
For admin use:

upd flag name to pruning-max-worldstate-num

---

store/rootmulti/store.go

Closes: #XXX
______
______
For admin use:

Fix pruning bug: forced type conversion out of bounds

---

store/types/pruning.go

Closes: #XXX
______
______
For admin use:

update pruning default value

---

go.mod
go.sum

Closes: #XXX
______
______
For admin use:

bump tendermint version

---

server/start_okchain.go

Closes: #XXX
______
______
For admin use:

add flags about websocket

---

server/config/config.go

Closes: #XXX
______
______
For admin use:

update gas price

---

server/config/config.go

Closes: #XXX
______
______
For admin use:

update default gas price

---

x/auth/keeper/account.go
x/auth/keeper/ante_okchain.go
x/auth/keeper/keeper.go

Closes: #XXX
______
______
For admin use:

update observer from accountKeeper

---

x/auth/client/utils/query.go

Closes: #XXX
______
______
For admin use:

fix query evm tx failed

---

baseapp/abci.go
baseapp/baseapp.go
baseapp/baseapp_test.go
baseapp/helpers.go
simapp/test_helpers.go
store/rootmulti/store.go
x/mock/test_utils.go

Closes: #XXX
______
______
For admin use:

fix not support to simulate tx with specifying block height(without smb)

---

x/auth/client/utils/query.go

Closes: #XXX
______
______
For admin use:

fix parse apptx

---

x/auth/client/utils/query.go

Closes: #XXX
______
______
For admin use:

fix query tx failed (#747)

---

client/keys/add.go

Closes: #XXX
______
______
For admin use:

fix keys recover bug

---

baseapp/baseapp.go
types/errors/abci.go
types/errors/abci_test.go
types/errors/errors.go

Closes: #XXX
______
______
For admin use:

fix simulate tx with height

---

baseapp/baseapp.go
baseapp/options.go
types/handler.go
x/auth/types/stdtx.go

Closes: #XXX
______
______
For admin use:

add nonce support for cm tx

---

store/rootmulti/store.go

Closes: #XXX
______
______
For admin use:

support prune app store

---

store/rootmulti/store.go

Closes: #XXX
______
______
For admin use:

Merge  PR: support prune app store (#136)

---

server/start.go
store/iavl/store.go

Closes: #XXX
______
______
For admin use:

optimize the size of iavl cache

---

client/flags/flags.go
server/start_okchain.go

Closes: #XXX
______
______
For admin use:

add default path in flag

---

baseapp/baseapp.go
types/milestone.go
x/auth/ante/fee.go
x/auth/types/stdtx.go

Closes: #XXX
______
______
For admin use:

 deprecate homestead signer

---

baseapp/baseapp.go

Closes: #XXX
______
______
For admin use:

rewrite error code after runMsg

---

baseapp/baseapp.go

Closes: #XXX
______
______
For admin use:

add mercury height for code

---

baseapp/baseapp.go
client/flags/flags.go
server/start_okchain.go
types/milestone.go
x/auth/ante/fee.go
x/auth/types/stdtx.go

Closes: #XXX
______
______
For admin use:

update code from main branch

---

store/rootmulti/store.go

Closes: #XXX
______
______
For admin use:

pruning optimize

---

server/start.go
server/util.go

Closes: #XXX
______
______
For admin use:

fix dynamic config bug

---

server/start.go

Closes: #XXX
______
______
For admin use:

add leveldb config

---

baseapp/baseapp.go
server/start.go
types/context.go

Closes: #XXX
______
______
For admin use:

Pending pool feature

---

server/start.go
x/auth/types/account_retriver_exchain.go

Closes: #XXX
______
______
For admin use:

Mempool pending

---

baseapp/baseapp.go
server/start.go

Closes: #XXX
______
______
For admin use:

add support to retrieve tx info

---

x/auth/ante/sigverify.go

Closes: #XXX
______
______
For admin use:

fix sending cosmos tx to pending pool

---

baseapp/baseapp.go

Closes: #XXX
______
______
For admin use:

fix the slow return when simulate tx on specified height

---

server/start.go
store/rootmulti/store.go

Closes: #XXX
______
______
For admin use:

issue-786 add flags to set iavl params

---

baseapp/abci.go
go.mod
go.sum
server/mock/store.go
server/start.go
store/iavl/store.go
store/iavl/tree.go
store/rootmulti/dbadapter.go
store/rootmulti/store.go
store/transient/store.go
store/types/store.go

Closes: #XXX
______
______
For admin use:

change interfaces to receive logs from iavl

---

go.mod
go.sum
server/start.go

Closes: #XXX
______
______
For admin use:

add iavl flag: EnablePruningHistoryState, add log

---

baseapp/abci.go

Closes: #XXX
______
______
For admin use:

limit gas used

---

baseapp/abci.go
go.mod
go.sum
server/mock/store.go
store/iavl/store.go
store/iavl/tree.go
store/rootmulti/dbadapter.go
store/rootmulti/store.go
store/transient/store.go
store/types/store.go

Closes: #XXX
______
______
For admin use:

getnode count
